services:
  - type: web
    name: inventario-motores
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python3.11
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
